version: '3'
services:
  node_front:
    image: salud-en-movimiento-front
    build:
      context: ./
      dockerfile: node_prod.Dockerfile
    environment:
      NODE_ENV: production
      VITE_API_URL: "https://salud-en-movimiento.com.ar/api/v1"
    ports:
      - "5173:80"
    restart: always