service: sample-app
provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: us-east-1
  memorySize: 128
functions:
  app:
    handler: dist/index.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}